### ISSUE TITLE
Depending on height, have more power on the output for the grabber

### ISSUE THREAD

**Issue by ChrisHirsch** [Raptacon/Robot-2023#113]
The Drive team is requesting to have the "grabber" output with more  power as it attempts to deliver to mid or back. Talk to the drive team for more details.

**Comment by ChrisHirsch** [comment]
Ask Travis for exact details

**Comment by ChrisHirsch** [comment]
We're already at full speed and currently the gearing is 1:1. Post Utah, we should probably change gearing so we have more torque and can then meet these needs.

**Comment by ChrisHirsch** [comment]
Current Limit is currently 25A so "i'm giving her all she's got captain"

**Comment by tuffinmuffin** [comment]
32 amps*

**Comment by ChrisHirsch** [comment]
No longer needed because we have a legit working arm now
