### ISSUE TITLE
Need to call pid.reset() in GoToDist init()

### ISSUE THREAD

**Issue by ChrisHirsch** [Raptacon/Robot-2023#148]
There is a problem with the PID is GoToDist init that if we are using it and there are existing pid errors, the "drive" will attempt to correct on accumulated errors. 

ie [acceleration](https://giphy.com/gifs/70s-dukes-of-hazzard-the-eppZg5SmXd5Na5QXZu)

Instead an explicit [pid.reset()](https://github.com/Raptacon/Robot-2023/blob/main/commands/goToDist.py#L25) should be called in the [init()](https://github.com/Raptacon/Robot-2023/blob/main/commands/goToDist.py#L22) method to avoid this.

We saw then when using the CENTER position in autonomous and the bot did it it's stuff and then accelerated VERY quickly

**Comment by DanteSGarrett** [comment]
This issue is obsolete because we are now using swerve.
