### ISSUE TITLE
Acturator error on teapot

### ISSUE THREAD

**Issue by Leaf-life** [Raptacon/Robot-2023#32]
### Description
deploying 2022 code to teapot their is an error about the actuator

### Steps to Reproduce

1. deploy/ run sim of 2022 code to teapot

**Expected behavior:**
no errors when deploying the 2022 code to teapot

**Actual behavior:** 
actuator error

### Required Information

- What tag/branch/release of Robot code are you using?
  2022 base code

### Useful Information

- latest wiplib and python

**Comment by ChrisHirsch** [comment]
obsolete and we're into 2023 code now
